Output assets/cmdpeek-search-scroll-demo.gif

Set Shell "zsh"
Set FontSize 30
Set Width 2800
Set Height 1800
Set TypingSpeed 60ms
Set Theme "Dracula"

Require cmdpeek

Type "cmdpeek"
Enter
Sleep 2s

Type "/"
Sleep 700ms

Type "example"
Sleep 1.5s

Enter
Sleep 2s

Type "123"
Sleep 800ms
Ctrl+Down
Sleep 500ms
Ctrl+Down
Sleep 500ms
Ctrl+Down
Sleep 500ms
Ctrl+Down
Sleep 500ms
Ctrl+Down
Sleep 1.5s
Enter
Sleep 2s

Enter
Sleep 5s

Type "y"
Sleep 500ms
Enter
Sleep 3s
