Output assets/cmdpeek-search-demo-filter.gif

Set Shell "zsh"
Set FontSize 18
Set Width 1800
Set Height 800
Set TypingSpeed 60ms
Set Theme "Dracula"

Require cmdpeek

Type "clear"
Enter
Sleep 500ms

Type "If your search returns multiple results, cmdpeek opens the filtered command list."
Ctrl+C
Sleep 1s

Type "cmdpeek elastic"
Enter
Sleep 2s
Down
Sleep 700ms
Enter
Sleep 700ms

Ctrl+C
Sleep 1s

Type "clear"
Enter
Sleep 500ms

Type "If your search returns a single result, cmdpeek opens that command directly."
Ctrl+C
Sleep 1s

Type "cmdpeek gif"
Enter
Sleep 2s

Type "file.gif"
Enter
Sleep 1s

Type "file.mp4"
Enter
Sleep 1s

Ctrl+C
Sleep 1s
